// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cockroachlabs/managed-service/console/api/admitter (interfaces: Service)

// Package admitter is a generated GoMock package.
package admitter

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// LoginCheck mocks base method
func (m *MockService) LoginCheck(arg0 string, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginCheck", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoginCheck indicates an expected call of LoginCheck
func (mr *MockServiceMockRecorder) LoginCheck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginCheck", reflect.TypeOf((*MockService)(nil).LoginCheck), arg0, arg1)
}
